dist: xenial

env:
  global:
  - HUGO_VERSION=0.55.1  # set in the environment to make it easy 

before_install:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz -o hugo.tar.gz
  - tar xzvvf hugo.tar.gz -C ./

script:
  - ./hugo 
deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: havron/min # This is the slug of the repo you want to deploy your site to
  target_branch: gh-pages # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: sgh65@cornell.edu
  name: "havron"
  keep-history: true
  on:
    branch: master
