baseurl = "https://havron.xyz/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Alexis Tacnet"
title = "Sam Havron"
disqusshortname = ""
pluralizelisttitles = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe= true

[permalinks]
blog = "writing/:slug/"

[params]
exclude_headings = ["rrg"]
footerFormat = "2006-Jan-02"
titlestyle = "capitalize"
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
copyright = ""
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
#logofile = "img/logo.png"
logofile = "img/self.jpg"
faviconfile = "img/favicon.ico"
highlightjs = true
progressively = true
share = false
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
# latestpostcount = 0
email = "havron@cs.cornell.edu"
github = "havron"
#linkedin = "john-example-aa80ue8è"
twitter = "SamHavron"
#facebook = "facebook_id"
#instagram = "instagram_id"
#itch_io = "itch_io_id"
#social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
#githubRepo = "stopipv/isdi/tree/master"
small_banner_logo = true # global, set large_banner_logo in a post to override this

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
